apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-service-ca
  name: service-ca-controller-config
data:
  controller-config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
