---
# run-workloads tasks

- name: Resolve prometheus endpoint
  ansible.builtin.include_tasks: roles/common/tasks/prometheus-endpoint.yml
  when: kube_burner_metrics_enabled | bool

- name: Clone e2e-benchmarking repository
  ansible.builtin.git:
    repo: "{{ e2e_repo }}"
    dest: "{{ e2e_path }}"
    version: "{{ e2e_git_revision }}"

- name: Run kube-burner workloads
  ansible.builtin.include_tasks: kube-burner.yml
  loop: "{{ workloads_to_run }}"
  loop_control:
    loop_var: kube_burner_workload
