images:
  - name: quay.io/openshift/sriov-network-operator
    newName: registry.redhat.io/openshift4/ose-sriov-network-rhel9-operator
    digest: sha256:18359efc7103351d57bcc0d1bad9a275cfb09b88b6074cf9283f9e5d70bc54ef

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SRIOV_CNI_IMAGE
          value: registry.redhat.io/openshift4/sriov-cni-rhel9@sha256:1946f74f425b12257ef85a9d67242e7e8342f240b7ac80241d18b1c568a4690c
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SRIOV_DEVICE_PLUGIN_IMAGE
          value: registry.redhat.io/openshift4/ose-sriov-network-device-plugin-rhel9@sha256:5f509d0a8a5686a2940fe3f0905c17dddc6c00d955743e2a2d9cf14ade18ae10
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: NETWORK_RESOURCES_INJECTOR_IMAGE
          value: registry.redhat.io/openshift4/ose-sriov-dp-admission-controller-rhel9@sha256:55592e1ad668c2a3cccbe47582e828bebec2798231809adff84efed2f399a7cc
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SRIOV_NETWORK_CONFIG_DAEMON_IMAGE
          value: registry.redhat.io/openshift4/ose-sriov-network-config-daemon-rhel9@sha256:b6d2e571dc60d98bc0292a6053d03dcf40bd2a4570b26a44e1d7d9a09a56390b
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SRIOV_NETWORK_WEBHOOK_IMAGE
          value: registry.redhat.io/openshift4/ose-sriov-network-webhook-rhel9@sha256:8aaaea5c03c4907bd328ff2e3c93c0607a121e76561fbbc36a65185f40c7944b
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SRIOV_INFINIBAND_CNI_IMAGE
          value: registry.redhat.io/openshift4/ose-sriov-infiniband-cni-rhel9@sha256:c71dfe1f2c986f838be6dbdf25c09920228a3c4057b4fa97ac5ece3712be0162
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: RDMA_CNI_IMAGE
          value: registry.redhat.io/openshift4/ose-sriov-rdma-cni-rhel9@sha256:aacea70d934ae017144c8062e049382d5c4cad37e099e676803948b3743df357
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: METRICS_EXPORTER_IMAGE
          value: registry.redhat.io/openshift4/ose-sriov-network-metrics-exporter-rhel9@sha256:0747c3151c5ec4e118d954505222364a85e66e0e7c34cd27b52705b3d87f2cbe
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: METRICS_EXPORTER_KUBE_RBAC_PROXY_IMAGE
          value: registry.redhat.io/openshift4/ose-kube-rbac-proxy-rhel9@sha256:54d33b9efe0867328de774ed049be40275c0bf8fea65d4ac5b319e99e2374b0f
    target:
      kind: Deployment
      name: sriov-network-operator
      namespace: sriov-network-operator
