
images:
  - name: quay.io/operator-framework/olm
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:5c784520b30b6c73ee5dcb9609daa718cf3bca454a3672ba0ceafec7f08efa30
  - name: quay.io/operator-framework/configmap-operator-registry
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:616b80177a517b0e555ec8a67d5a884cc511b280581ce0addc7ca7293433558a
  - name: quay.io/openshift/origin-kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:9e2ea30797381e916254735ae3fe98233a2b83f2d9b76388a40c700ec1bface4

patches:
  - patch: |-
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OPERATOR_REGISTRY_IMAGE
         value: quay.io/openshift-release-dev/ocp-v5.0-art-dev@sha256:616b80177a517b0e555ec8a67d5a884cc511b280581ce0addc7ca7293433558a
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OLM_IMAGE
         value: quay.io/openshift-release-dev/ocp-v5.0-art-dev@sha256:5c784520b30b6c73ee5dcb9609daa718cf3bca454a3672ba0ceafec7f08efa30
    target:
      kind: Deployment
      labelSelector: app=catalog-operator
