
images:
  - name: quay.io/operator-framework/olm
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:c0a58c35cfd757e35885fd989250efa107b026b6ff69b1b182d81bde7ba455b3
  - name: quay.io/operator-framework/configmap-operator-registry
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:ddec814221e3d4276f34681a0bebd9873d79cd11ccfa20b31b35da1f7edbd1f0
  - name: quay.io/openshift/origin-kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:3e8023c143295632c53e2e40009452e042cbc56fa0126db7cc27a9092d84bbb3

patches:
  - patch: |-
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OPERATOR_REGISTRY_IMAGE
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ddec814221e3d4276f34681a0bebd9873d79cd11ccfa20b31b35da1f7edbd1f0
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OLM_IMAGE
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:c0a58c35cfd757e35885fd989250efa107b026b6ff69b1b182d81bde7ba455b3
    target:
      kind: Deployment
      labelSelector: app=catalog-operator
