
images:
  - name: quay.io/operator-framework/olm
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:3e20100091d70b8a635212d4eed61856c129439557591b9e982b68794c98ddc3
  - name: quay.io/operator-framework/configmap-operator-registry
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:60764718c36d6f4ef4118e3b5ced7fbb833fae6f6f1d48156437a00d81d1c8ad
  - name: quay.io/openshift/origin-kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:5db166ba6e6588cbfb0621423c2f8ab4d28fc172bf2cc070a1fd4b7707613879

patches:
  - patch: |-
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OPERATOR_REGISTRY_IMAGE
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:60764718c36d6f4ef4118e3b5ced7fbb833fae6f6f1d48156437a00d81d1c8ad
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OLM_IMAGE
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3e20100091d70b8a635212d4eed61856c129439557591b9e982b68794c98ddc3
    target:
      kind: Deployment
      labelSelector: app=catalog-operator
