#!/bin/sh

mkdir -p bin

cd src
GOPATH=${GOPATH:-$(go env GOPATH)}
OUTPUT_DIR=${GOPATH}/src/github.com/flannel-io/cni-plugin/dist
CGO_ENABLED=0 GOOS=linux GOARCH=$1 scripts/build_flannel.sh && mv ${OUTPUT_DIR}/flannel-$1 ../bin/flannel-$1

