
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:1c04c7e07a9ef24deaf389f31faafb62424253317e4f329d31469cfb9321f414
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:6be68d92ccde218752f24c3f089c2f392f209e1243dd0d75839d62b9930e34b7
