
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:962d8fc2c20942d17562e18f72404a9acee9ae679ee235b54adeed324ccf19a2
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:6265cd10bc1fc465456c37310a775e52bd99ebfee8604520f651778e262f9aa0
