---
- name: Initialize results directory
  ansible.builtin.include_tasks: roles/common/tasks/results-dir.yml

- name: Disk space block
  block:
    - name: Find disk usage
      become: true
      ansible.builtin.shell:
        cmd: du -BM -t 1M --max-depth=1 {{ item }} | sort -rh
      register: disk_usage

    - name: Print disk_usage var
      ansible.builtin.debug:
        var: disk_usage.stdout_lines

    - name: Add disk info to local file
      ansible.builtin.lineinfile:
        path: "{{ results_dir }}/{{ filename }}"
        line: "{{ disk_item }}"
        create: true
      delegate_to: localhost
      with_items:
        - "{{ item }}:"
        - "{{ disk_usage.stdout_lines }}"
      loop_control:
        loop_var: disk_item
