# the pull secret is mandatory for MicroShift builds on top of OpenShift
# for community builds on top of OKD, this setting has no effect
[crio.image]
global_auth_file="/etc/crio/openshift-pull-secret"
pause_image = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4ef9645ef3e21db91709305a01d9918423fa19c000f33b803067e0f49163662a"
pause_image_auth_file = "/etc/crio/openshift-pull-secret"
pause_command = "/usr/bin/pod"
