# the pull secret is mandatory for MicroShift builds on top of OpenShift
# for community builds on top of OKD, this setting has no effect
[crio.image]
global_auth_file="/etc/crio/openshift-pull-secret"
pause_image = "quay.io/openshift-release-dev/ocp-v5.0-art-dev@sha256:d7873856926679be693e577d695a9cf8b0b045590df15e98cdafc796c7858948"
pause_image_auth_file = "/etc/crio/openshift-pull-secret"
pause_command = "/usr/bin/pod"
