# the pull secret is mandatory for MicroShift builds on top of OpenShift
# for community builds on top of OKD, this setting has no effect
[crio.image]
global_auth_file="/etc/crio/openshift-pull-secret"
pause_image = "quay.io/openshift-release-dev/ocp-v5.0-art-dev@sha256:0fce24e56e4dae05f2bcf354629803b6f56fd3642c5c4a8e4b14e1ab89f76c81"
pause_image_auth_file = "/etc/crio/openshift-pull-secret"
pause_command = "/usr/bin/pod"
