#!/bin/sh
set -e
mkdir -p bin

cd src

if [ "x$1" == "xarm" ]; then
  git apply ../arm32.patch
fi

set -x

GOOS=linux GOARCH=$1 CGO_ENABLED=0  GOFLAGS="-mod=vendor" \
  go build -a -ldflags '-extldflags "-static"' -o ../bin/hostpath-provisioner-"$1" cmd/provisioner/hostpath-provisioner.go

set +x

if [ "x$1" == "xarm" ]; then
  git stash
  git clean -f
fi

