images:
  - name: quay.io/openshift/kube-metrics-server
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:5051450eacd8544c4274f83dcebb34b78deea48cd661bf14c61557398670984c
