apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 01-serviceaccount.yaml
  - 02-clusterrole.yaml
  - 03-clusterrolebinding.yaml
  - 04-rolebinding.yaml
  - 05-deployment.yaml
  - 06-service.yaml
  - 07-apiservice.yaml
