images:
  - name: quay.io/openshift/kube-metrics-server
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:5dcf7005ef99410122be8b929c9424548c205c3781def8ab4afa7a5495564a5b
