apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - cluster-role-binding-auth-delegator.yaml
  - role-binding-auth-reader.yaml
  - configmap-audit-profiles.yaml
  - deployment.yaml
  - service.yaml
  - api-service.yaml
