#!/bin/sh

# $1 is ARCH but, we ignore this here, as we only build the riscv64 version

# TODO use our own image for riscv64 builder

podman run -it --rm -v $(pwd)/src:/src -e TAG="${VERSION}" -w /src carlosedp/crossbuild-riscv64 <<EOF
cd build/pause
mkdir -p bin
riscv64-linux-gcc -Os -Wall -Werror -static -DVERSION=v3.6 -o bin/pause-riscv64 pause.c
exit
EOF

cp -rfp src/build/pause/bin .
