#!/bin/bash

set -euxo pipefail

setsebool -P container_manage_cgroup true

if ! /usr/bin/podman volume exists microshift-persistent-data
then
  /usr/bin/podman volume create microshift-persistent-data
fi
