#!/bin/sh
set -e

mkdir -p bin

cd src

if [ "x$1" == "xriscv64" ]; then
  git apply ../0001-workaround-riscv64.patch
fi

set -x
GO111MODULE=on GOOS=linux GOARCH=$1 GOFLAGS="-mod=vendor" \
make build
set +x

cp _output/kube-rbac-proxy-linux-"$1" ../bin/kube-rbac-proxy-"$1"

if [ "x$1" == "xriscv64" ]; then
  git stash
  git clean -f
fi
