apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: openshift-monitoring
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: kube-state-metrics-tls
  labels:
    app.kubernetes.io/name: kube-state-metrics
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: kube-state-metrics
  ports:
    - name: https-main
      port: 8443
      targetPort: https-main
      protocol: TCP
    - name: https-self
      port: 9443
      targetPort: https-self
      protocol: TCP
