images:
  - name: quay.io/openshift/kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:68cec56cb3063126c3e988e4abc1c305a348fc6c71d082e1f517251754fb02a5
  - name: quay.io/openshift/kube-state-metrics
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:c6b503ea91e63a9dc4ea71ec53338375799201b7d877c40676d4b86679baf85f
