images:
  - name: quay.io/openshift/kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:9713eb4fb1142ca9346ab172c03a3be849bfa60c916d31d4f8701ea9895d9ae5
  - name: quay.io/openshift/kube-state-metrics
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:c96d65bef6ec598e51bca42c1ea9df2d9e46d020cef9e101942fe41024166a26
