images:
  - name: quay.io/openshift/kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:86cc666b6058f08da9009516d02b8028ab619281aa471b9e28a76d64d57f7486
  - name: quay.io/openshift/kube-state-metrics
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:fc32c059b1946f4bac26b6c8b68c2ca3802eba73244e85c38d756edbb16c658b
