apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-serviceaccount.yaml
  - 02-clusterrole.yaml
  - 03-clusterrolebinding.yaml
  - 04-deployment.yaml
  - 05-service.yaml
