images:
  - name: quay.io/openshift/kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:2129afeaf7fe8fa15f02eb4715badf0607b2f79c7e9e13cd9537992cb357a0d9
  - name: quay.io/openshift/kube-state-metrics
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:ac7ccd69ce16d68d49a2d1eb1c30d98c12735926e0810549002a855263fc407f
