FROM docker.io/alpine:latest

RUN apk add --no-cache tinyproxy \
 && apk add --no-cache nano

RUN cp /etc/tinyproxy/tinyproxy.conf /etc/tinyproxy/tinyproxy.conf.orig \
 &&  sed -r -e 's/^(Allow .+)$/#\1/g' -i /etc/tinyproxy/tinyproxy.conf \
 &&  sed -r -e 's/^(ViaProxyName .+)$/#\1/g' -i /etc/tinyproxy/tinyproxy.conf \
 &&  sed -r -e 's/^(MaxRequestsPerChild) 0$/\1 10000/g' -i /etc/tinyproxy/tinyproxy.conf

EXPOSE 8888
ENTRYPOINT ["/usr/bin/tinyproxy"]
CMD ["-d"]
