//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRenewalImpact) DeepCopyInto(out *CertificateRenewalImpact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRenewalImpact.
func (in *CertificateRenewalImpact) DeepCopy() *CertificateRenewalImpact {
	if in == nil {
		return nil
	}
	out := new(CertificateRenewalImpact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRenewalItem) DeepCopyInto(out *CertificateRenewalItem) {
	*out = *in
	if in.ParentCA != nil {
		in, out := &in.ParentCA, &out.ParentCA
		*out = new(string)
		**out = **in
	}
	in.CurrentNotAfter.DeepCopyInto(&out.CurrentNotAfter)
	in.NewNotAfter.DeepCopyInto(&out.NewNotAfter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRenewalItem.
func (in *CertificateRenewalItem) DeepCopy() *CertificateRenewalItem {
	if in == nil {
		return nil
	}
	out := new(CertificateRenewalItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRenewalResult) DeepCopyInto(out *CertificateRenewalResult) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.GeneratedAt.DeepCopyInto(&out.GeneratedAt)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertificateRenewalItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Impact = in.Impact
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRenewalResult.
func (in *CertificateRenewalResult) DeepCopy() *CertificateRenewalResult {
	if in == nil {
		return nil
	}
	out := new(CertificateRenewalResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificateRenewalResult) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateStatusConfig) DeepCopyInto(out *CertificateStatusConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateStatusConfig.
func (in *CertificateStatusConfig) DeepCopy() *CertificateStatusConfig {
	if in == nil {
		return nil
	}
	out := new(CertificateStatusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateStatusItem) DeepCopyInto(out *CertificateStatusItem) {
	*out = *in
	in.NotBefore.DeepCopyInto(&out.NotBefore)
	in.NotAfter.DeepCopyInto(&out.NotAfter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateStatusItem.
func (in *CertificateStatusItem) DeepCopy() *CertificateStatusItem {
	if in == nil {
		return nil
	}
	out := new(CertificateStatusItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateStatusList) DeepCopyInto(out *CertificateStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.GeneratedAt.DeepCopyInto(&out.GeneratedAt)
	out.Config = in.Config
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertificateStatusItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateStatusList.
func (in *CertificateStatusList) DeepCopy() *CertificateStatusList {
	if in == nil {
		return nil
	}
	out := new(CertificateStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificateStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Error) DeepCopyInto(out *Error) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.GeneratedAt.DeepCopyInto(&out.GeneratedAt)
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Error.
func (in *Error) DeepCopy() *Error {
	if in == nil {
		return nil
	}
	out := new(Error)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Error) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
