#!/bin/bash

set -euxo pipefail

microshift_start() {
setsebool -P container_manage_cgroup true

if ! /usr/bin/podman volume exists microshift-data
then
  /usr/bin/podman volume create microshift-data
fi

/usr/bin/podman run -d --rm \
  --name microshift-aio --privileged \
  -v /lib/modules:/lib/modules \
  -v microshift-data:/var/lib \
  --label "io.containers.autoupdate=registry" \
  -p 6443:6443 quay.io/microshift/microshift:4.7.0-0.microshift-2021-08-31-224727-aio

[[ -d /etc/microshift-aio ]] || mkdir /etc/microshift-aio
cat <<EOF > /etc/microshift-aio/microshift-aio.conf
export KUBECONFIG=$(/usr/bin/podman volume inspect microshift-data --format "{{.Mountpoint}}")/microshift/resources/kubeadmin/kubeconfig
EOF
}

microshift_stop() {
    /usr/bin/podman stop -t 20 microshift-aio
}

arg="$1"
if [[ $arg == "start" ]]
then
  microshift_start
elif [[ $arg == "stop" ]]
then
  microshift_stop
else
  echo "$arg: unknown argument-only allowed 'start' and 'stop'"
  exit 1
fi
