apiVersion: v1
kind: Namespace
metadata:
  name: openshift-c2cc
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  annotations:
    openshift.io/node-selector: ""
    workload.openshift.io/allowed: "management"
