apiVersion: v1
kind: Service
metadata:
  namespace: microshift-c2cc
  name: c2cc-probe
spec:
  clusterIP: '{{ .ProbeServiceClusterIP }}'
  ports:
  - name: probe
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: c2cc-probe
