apiVersion: v1
kind: Service
metadata:
  namespace: openshift-c2cc
  name: c2cc-probe
spec:
  clusterIP: '{{ .ProbeServiceClusterIP }}'
{{- if .DualStack }}
  ipFamilyPolicy: RequireDualStack
  clusterIPs:
  - '{{ .ProbeServiceClusterIP }}'
  - '{{ .ProbeServiceClusterIPSecondary }}'
{{- end }}
  ports:
  - name: probe
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: c2cc-probe
