FROM quay.io/microshift/busybox:1.36

ARG USERNAME=microshift
ARG GROUPNAME=$USERNAME
ARG USER_UID=1001
ARG USER_GID=$USER_UID

# Create the user
RUN addgroup -g $USER_GID $GROUPNAME \
    && adduser -u $USER_UID -G $GROUPNAME -D $USERNAME 

USER $USERNAME

WORKDIR /e2e
RUN echo "MicroShift Test" > index.html

EXPOSE 8080
ENTRYPOINT [ "/bin/sh" ]
CMD [ "-c", "httpd -f -p 8080 -h /e2e" ]
