FROM registry.access.redhat.com/ubi9:latest
USER root
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN printf '%s\n' \
    '[google-cloud-sdk]' \
    'name=Google Cloud SDK' \
    'baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64' \
    'enabled=1' \
    'gpgcheck=1' \
    'repo_gpgcheck=1' \
    'gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg' \
    '      https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg' > /etc/yum.repos.d/google-cloud-sdk.repo
RUN dnf update -y && \
    dnf install --setopt=tsflags=nodocs -y \
        diffutils \
        gcc \
        git \
        glibc-static \
        google-cloud-cli \
        jq \
        make \
        python3-pip \
        util-linux && \
    dnf clean all && rm -rf /var/cache/dnf/*
