apiVersion: v1
kind: Secret
metadata:
  namespace: openshift-monitoring
  name: metrics-server-client-certs
  annotations:
    openshift.io/owning-component: metrics-server
type: kubernetes.io/tls
data:
  tls.crt:
  tls.key:
