
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:5167f732098db1ef863656cd301e75fe83e858f6d2c1bb7705967ad8400b0200
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:367eda543131d62a1caebffd181c9fb9ef43ae254dde1f1478809ba23c922504
