
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:3224abad69c5eefbf556292c02490bc4d379df4297e26f7185042af7c5f7098f
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:bc0cbcc3d203b9533ea5ff13de8dff460e781473aa582f1f4b2555efd79f97ee
