
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:a6500340efc0a4eaa3e4a501e2427cbd2b8d55c0ccbfe8af463484120de6c8fb
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:bd5d088354e63d3be7336255c8e32fc6d5f063bc7dfc9421c14cd65763848875
