
images:
  - name: multus-cni-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:03c15cf6f9b94a6e17b8d4865324860d66b79b315b2d587fddb6fc2b06c256ce
  - name: containernetworking-plugins-microshift
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:c9228724948c6c74686408919d6fdf29ffdccb1b35132717a362ab2bf419123e
