apiVersion: v1
kind: Namespace
metadata:
  name: openshift-monitoring
  labels:
    name: openshift-monitoring
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
