apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: openshift-monitoring
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: node-exporter-tls
  labels:
    app.kubernetes.io/name: node-exporter
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: node-exporter
  ports:
    - name: https
      port: 9101
      targetPort: https
      protocol: TCP
