images:
  - name: quay.io/openshift/kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:17cebedd4c367120b4a1e4d18a527ab32be9e2174efc0853c3f5d4d6f99bc4c1
  - name: quay.io/openshift/node-exporter
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:62fc265c6e2352dd8092fa3f1fc5ebb2c81c0e9e70497d26228aafaef077cb29
