images:
  - name: quay.io/openshift/kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:ce7fa5ab7b13cdf48cc9c9322374d902dc21cf33e1e7004c333fa4cdee789464
  - name: quay.io/openshift/node-exporter
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:ef715f41206bd4a75b104774fb3394a9851ca8fd98763ad69a3bdaf1983c412d
