images:
  - name: quay.io/openshift/kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:27dbc2e09e18558792be07768fdbd9f9d852e03ad829055c36ceb5be24bbccfd
  - name: quay.io/openshift/node-exporter
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:953ed7aea72d22367bfde4ccd9edf5764f19b0b54365d61e3fe796391bc974a4
