images:
  - name: quay.io/openshift/kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:037e74e6b8d44ed823e1f0a00a304a03ee8e74cf9691cc9d167f5af207dce946
  - name: quay.io/openshift/node-exporter
    newName: quay.io/openshift-release-dev/ocp-v5.0-art-dev
    digest: sha256:2dae7a1e86f7619a2f3bb1f2c54d2ea230746957fde0faa2b9edc79960fab7fe
