{
 "title": "MicroShift Telemetry",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "offline_threshold", "label": "Offline period threshold", "query": "2h,6h,12h,1d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "About this dashboard",
   "type": "text",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 0 },
   "options": {
    "content": "* The majority of MicroShift use cases is disconnected environments. Data below represents a small fraction of clusters.\n* Telemetry feature was introduced in 4.19. There is no data prior to that version.\n* A cluster is considered to be offline when it stops reporting metrics.\n  * `Offline period threshold` is a configurable option to establish how long a cluster can stop reporting metrics until it is considered to be offline.\n* Short lived clusters (<1h uptime) are explicitly excluded from production info.\n  * CI and QE run some tests on production servers for quality assurance. These clusters are short lived.\n* Non-production clusters belong to CI and QE."
   }
  },
  { "title": "Production clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Active clusters",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (\n  max by (_id, version) (\n    count_over_time(microshift_version[$offline_threshold]) > 0\n  )\n  and on(_id)\n  (\n    max by (_id) (\n      count_over_time(microshift_version[$offline_threshold]) > 0\n    )\n    unless on (_id)\n    (\n      (\n        max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n        -\n        min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      ) < 3600\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active clusters",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count (\n  max by (_id, version) (\n    count_over_time(microshift_version[$offline_threshold]) > 0\n  )\n  and on(_id)\n  (\n    max by (_id) (\n      count_over_time(microshift_version[$offline_threshold]) > 0\n    )\n    unless on (_id)\n    (\n      (\n        max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n        -\n        min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      ) < 3600\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active clusters",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  (\n    max by (_id) (max_over_time(cluster:capacity_cpu_cores:sum{label_beta_kubernetes_io_instance_type=\"rhde\"}[$offline_threshold:5m]))\n    unless on (_id)\n    (\n      (\n        max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n        - \n        min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      ) < 3600\n    )\n  ) <= 4\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(\n  (\n    (\n      max by (_id) (max_over_time(cluster:capacity_cpu_cores:sum{label_beta_kubernetes_io_instance_type=\"rhde\"}[$offline_threshold:5m]))\n      and on(_id)\n  (\n    max by (_id) (\n      count_over_time(microshift_version[$offline_threshold]) > 0\n    )\n    unless on (_id)\n    (\n      (\n        max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n        -\n        min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      ) < 3600\n    )\n  )\n    ) > 4\n    and\n    (\n      max by (_id) (max_over_time(cluster:capacity_cpu_cores:sum{label_beta_kubernetes_io_instance_type=\"rhde\"}[$offline_threshold:5m]))\n      and on(_id)\n  (\n    max by (_id) (\n      count_over_time(microshift_version[$offline_threshold]) > 0\n    )\n    unless on (_id)\n    (\n      (\n        max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n        -\n        min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      ) < 3600\n    )\n  )\n    ) <= 8\n  )\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(\n  (\n    (\n      max by (_id) (max_over_time(cluster:capacity_cpu_cores:sum{label_beta_kubernetes_io_instance_type=\"rhde\"}[$offline_threshold:5m]))\n      and on(_id)\n      (\n        max by (_id) (\n          count_over_time(microshift_version[$offline_threshold]) > 0\n        )\n        unless on (_id)\n        (\n          (\n            max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n            -\n            min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n          ) < 3600\n        )\n      )\n    ) > 8\n    and\n    (\n      max by (_id) (max_over_time(cluster:capacity_cpu_cores:sum{label_beta_kubernetes_io_instance_type=\"rhde\"}[$offline_threshold:5m]))\n      and on(_id)\n      (\n        max by (_id) (\n          count_over_time(microshift_version[$offline_threshold]) > 0\n        )\n        unless on (_id)\n        (\n          (\n            max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n            -\n            min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n          ) < 3600\n        )\n      )\n    ) <= 16\n  )\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(\n  (\n    (\n      max by (_id) (max_over_time(cluster:capacity_cpu_cores:sum{label_beta_kubernetes_io_instance_type=\"rhde\"}[$offline_threshold:5m]))\n      and on(_id)\n  (\n    max by (_id) (\n      count_over_time(microshift_version[$offline_threshold]) > 0\n    )\n    and on(_id)\n    (\n      max by (_id) (\n        count_over_time(microshift_version[$offline_threshold]) > 0\n      )\n      unless on (_id)\n      (\n        (\n          max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n          -\n          min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n        ) < 3600\n      )\n    )\n  )\n    ) > 16\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster uptime",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 4, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  (\n    (\n      max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      - \n      min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n    ) > 3600\n    and\n    (\n      max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      - \n      min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n    ) <= 86400 # <1 day uptime.\n  )\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(\n  (\n    (\n      max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      - \n      min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n    ) > 86400\n    and\n    (\n      max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      - \n      min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n    ) <= 604800 # <1 week uptime.\n  )\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(\n  (\n    (\n      max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      - \n      min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n    ) > 604800\n    and\n    (\n      max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      - \n      min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n    ) <= 2592000 # < 1 month uptime.\n  )\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(\n  (\n    (\n      max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      - \n      min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n    ) > 2592000\n    and\n    (\n      max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      - \n      min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n    ) <= 15552000 # < 6 month uptime.\n  )\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(\n  (\n    (\n      max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      - \n      min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n    ) > 15552000\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active CPUs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  max by (_id) (\n    max_over_time(cluster:capacity_cpu_cores:sum{label_beta_kubernetes_io_instance_type=\"rhde\"}[$offline_threshold:5m])\n  )\n  and on(_id)\n  (\n    max by (_id) (\n      count_over_time(microshift_version[$offline_threshold]) > 0\n    )\n    unless on (_id)\n    (\n      (\n        max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n        -\n        min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      ) < 3600\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active CPUs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  max by (_id) (\n    max_over_time(cluster:capacity_cpu_cores:sum{label_beta_kubernetes_io_instance_type=\"rhde\"}[$offline_threshold:5m])\n  )\n  and on(_id)\n  (\n    max by (_id) (\n      count_over_time(microshift_version[$offline_threshold]) > 0\n    )\n    unless on (_id)\n    (\n      (\n        max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n        -\n        min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      ) < 3600\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPUs by architecture",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (label_kubernetes_io_arch) (\n  max by (_id, label_kubernetes_io_arch) (\n    max_over_time(cluster:capacity_cpu_cores:sum{label_beta_kubernetes_io_instance_type=\"rhde\"}[$offline_threshold:5m])\n  )\n  and on(_id)\n  (\n    max by (_id) (\n      count_over_time(microshift_version[$offline_threshold]) > 0\n    )\n    unless on (_id)\n    (\n      (\n        max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n        -\n        min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      ) < 3600\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters by version and type",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (deployment_type, version) (\n  (\n    count_over_time(microshift_version[$offline_threshold]) > 0\n  )\n  and on(_id)\n  (\n    max by (_id) (\n      count_over_time(microshift_version[$offline_threshold]) > 0\n    )\n    unless on (_id)\n    (\n      (\n        max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n        -\n        min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      ) < 3600\n    )\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster deployment types",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (deployment_type) (\n  (\n    count_over_time(microshift_version[$offline_threshold]) > 0\n  )\n  and on(_id)\n  (\n    max by (_id) (\n      count_over_time(microshift_version[$offline_threshold]) > 0\n    )\n    unless on (_id)\n    (\n      (\n        max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n        -\n        min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      ) < 3600\n    )\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster versions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 7, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (version) (\n  (\n    count_over_time(microshift_version[$offline_threshold]) > 0\n  )\n  and on(_id)\n  (\n    max by (_id) (\n      count_over_time(microshift_version[$offline_threshold]) > 0\n    )\n    unless on (_id)\n    (\n      (\n        max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n        -\n        min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      ) < 3600\n    )\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Non-production clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Created clusters",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  (\n    count_over_time(microshift_version[$offline_threshold]) > 0\n  )\n  and on(_id)\n  (\n    max by (_id) (\n      count_over_time(microshift_version[$offline_threshold]) > 0\n    )\n    unless on (_id)\n    (\n      (\n        max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n        -\n        min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      ) >= 3600\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active clusters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  (\n    count_over_time(microshift_version[$offline_threshold]) > 0\n  )\n  and on(_id)\n  (\n    max by (_id) (\n      count_over_time(microshift_version[$offline_threshold]) > 0\n    )\n    unless on (_id)\n    (\n      (\n        max by(_id) (max_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n        -\n        min by(_id) (min_over_time(timestamp(microshift_version)[$offline_threshold:5m]))\n      ) >= 3600\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}