# BUILD STAGE
FROM registry.access.redhat.com/ubi8/go-toolset as builder

USER root

LABEL name=microshift-build

ENV GOPATH=/opt/app-root GOCACHE=/mnt/cache GO111MODULE=on

WORKDIR $GOPATH/src/github.com/openshift/microshift

COPY . .

RUN wget https://go.dev/dl/go1.18.1.linux-amd64.tar.gz && \
    rm -rf /usr/bin/go && rm -rf /usr/local/go && \
    tar -C /usr/local -xzf go1.18.1.linux-amd64.tar.gz && \
    export PATH=$PATH:/usr/local/go/bin && \
    rm go1.18.1.linux-amd64.tar.gz && \
    make build

# RUN STAGE
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.4

COPY --from=builder /opt/app-root/src/github.com/openshift/microshift/microshift /usr/bin/microshift
COPY --from=builder /opt/app-root/src/github.com/openshift/microshift/sample-opentelemetry/otelcol-jaeger-microshift.sh /opt/otelcol-jaeger-microshift.sh
COPY --from=builder /opt/app-root/src/github.com/openshift/microshift/sample-opentelemetry/otelcol-service/config.yaml /opt/otelcol-config.yaml
